### ISSUE TITLE
Enable users to edit there membership details

### ISSUE THREAD

**Issue by oshotton** [SWAuk/com_swa#119] opened 2015-10-09 13:09 UTC
Allow people to change the basic info about themselves like DoB, Phone number, Dietary requirements etc. Obviously don't allow them to change the Paid flag!

Lot's of people been asking me to change DoB.
Roisin's dietary requirements had changed from the old site/never been set.

**Comment by addshore** [comment] 2015-10-11 12:34
Yep, need to do this soon as people are asking to change their level as well so they can buy the correct ticket!
Dietary requirements never used to be a thing on the old site :)

**Comment by addshore** [comment] 2015-10-28 08:16
Duplicate of #34

**Closed by addshore** 2015-10-28 08:16 UTC
Labels: enhancement
